# specify the namespace of the robot
robot_name: "oreo"

oreo:
  type: "Robot"
  name: "oreo"
  frame: "/base_link"

  # uncomment this line to get ground-truth semantic label
  # sensors: ["velodyne_vlp_16", "rgbcamera", "sick_laser", "hokuyo", "depthcamera", "semantic_camera", "fake_camera"]

  # initial pose
  translation: [0.0, 0.0, 0.5]
  rotation: [0.0, 0.0, 0.0, 1.0]

  # dynamic properties
  dynamic:
    mode: "dynamic" # dynamic: physical movement, legacy: override velocity

    navmesh: false  # moving on the navmesh only
    navmesh_offset: 0.0 # z-offset
    lock_rotation: false # lock the rotation in x and y, recommend true

    friction_coefficient: 0.1
    angular_damping: 0.3
    linear_damping: 0.3

  # geometrical properties for navmesh generation and collision, will be overwritten if collidable = True
  geometric:
    height: 1.0
    radius: 0.24

  # import 3D model
  model:
    model_path: "habitat_ros/robot/oreo/oreo" # the first section is the package name where the robot is placed in
    collidable: true  # recomment false if navmesh = true

  cmd_topic: "/cmd_vel"

  # switch to true to publish ground-truth tf between map and base_link
  publish_transfromation: false

  odom:
    topic: "/odometry_odm"
    frame: "/odom"
    child_frame: "/base_link"

    # randomly setted, could be modified if needed
    vel_cov: [
      [1.0,0.03,0.0,0.0,0.0,-0.02],
      [0.03,1.0,0.0,0.0,0.0,0.06],
      [0.0,0.0,1.0,0.0,0.0,0.0],
      [0.0,0.0,0.0,1.0,0.0,0.0],
      [0.0,0.0,0.0,0.0,1.0,0.0],
      [-0.02,0.06,0.0,0.0,0.0,1.0],]
    
  tf_links:
    base_footprint:
      frame: "/base_footprint"
      position: [0.0, 0.0, 0.0]
      orientation: [0.0, 0.0, 0.0, 1.0]