# specify the namespace of the robot
robot_name: "oreo"

oreo:
  type: "Robot"
  name: "oreo"
  frame: "/base_link"

  # the sensors param namespace
  sensors: ["velodyne_vlp_16", "rgbcamera", "sick_laser", "hokuyo", "depthcamera", "semantic_camera", "fake_camera"]

  translation: [0.0, 0.0, 0.5]
  rotation: [0.0, 0.0, 0.0, 1.0]

  # dynamic properties
  dynamic:
    mode: "legacy" # dynamic: physical movement, legacy: override velocity
    friction_coefficient: 0.0
    angular_damping: 0.5
    linear_damping: 0.65
    standing_force: 500.0 # constantly apply force downward to prevent falling

  # the first name is the package name
  model_path: "habitat_ros/robot/oreo/oreo"

  cmd_topic: "/cmd_vel"

  publish_transfromation: true

  odom:
    topic: "/odom"
    frame: "/odom"
    child_frame: "/base_link"
    
  tf_links:
    # base_link:
    #   frame: "/base_link"
    #   position: [0.0, 0.0, 0.0]
    #   orientation: [0.0, 0.0, 0.0, 1.0]

    base_footprint:
      frame: "/base_footprint"
      position: [0.0, 0.0, 0.0]
      orientation: [0.0, 0.0, 0.0, 1.0]