# The Velodyne VPL-16 discription file of the robot in habitat
velodyne_vlp_16:

  type: "3D_LiDAR"
  name: "velodyne_vlp_16"
  frame: "lidar"
  topic: "/velodyne_points"
  publish_transfromation: True
  position: [-0.175, 0.0, 1.2]

  sensor_info:

    far: 100.0
    near: 0.1

    vfov: 30
    hfov: 360

    mean_error: 0.02
    max_error: 0.03
    rate: 10

    resolution:
      vertical: 16
      horizontal: 3600
